# DATABASE/CONTENT LIMITS
TEXT_LIMIT = 4096
TEXT_MIN = 4
NAME_LIMIT = 80
NAME_MIN = 4
USERNAME_MIN = 4
USERNAME_LIMIT = 25
DESC_MIN = 4
DESC_LIMIT = 80
EMAIL_MIN = 6
EMAIL_LIMIT = 35
PER_PAGE = 3

# JSON API
RESOURCE_LIMIT = 25

# REQUEST METHODS
METHODS = ['GET', 'POST']

# CONFIG
DEFAULT_CONFIG = 0

# ERRORS
DEFAULT_SUBMISSION_ERR = 'Something went wrong. Check your submission for errors.'