name: Carafe - Static Analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: flake8
        run: |
          pip install flake8
          flake8 **/*.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 **/*.py --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics
